const ACTION_TYPES = {
  //counter
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_STEP: "SET_STEP",
  //to-do list
  CREATED_TASK: "CREATED_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  SET_FILTER_TASK: "SET_FILTER_TASK",
  SET_EDIT_DATA_TASK: "SET_EDIT_DATA_TASK",
  SAVE_EDIT_TASK: "SAVE_EDIT_TASK",
  //create user
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",
  //get users
  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_ERROR: "GET_USERS_ERROR",
  //get user
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR",

  // SET_SELECTED_USER: "SET_SELECTED_USER",
};

export default ACTION_TYPES;
