const ACTION_TYPES = {
  //counter
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_STEP: "SET_STEP",
  //to-do list
  CREATED_TASK: "CREATED_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  SET_FILTER_TASK: "SET_FILTER_TASK",
  SET_EDIT_DATA_TASK: "SET_EDIT_DATA_TASK",
  SAVE_EDIT_TASK: "SAVE_EDIT_TASK",
};

export default ACTION_TYPES;
